import { createElement, JSX, RefObject } from 'preact';
import { Transition, TransitionEffect } from './createTransition';
export interface ChildPropsOptions {
    current: boolean;
}
export interface Props extends JSX.HTMLAttributes<HTMLDivElement> {
    childProps?: (options: ChildPropsOptions) => any;
    children: JSX.Element | null;
    className?: string;
    effect?: TransitionEffect;
    pageClassName?: string;
    tagName?: string;
    uri: string;
}
export interface State {
    child: JSX.Element | null;
    index: number;
    lastChild: JSX.Element | null;
    rootRef: RefObject<HTMLDivElement>;
    transition: Transition | null;
    uri: string;
}
export declare function Swap({ childProps, children, effect, pageClassName, tagName, uri, ...props }: Props): import("preact").VNode<{
    ref: RefObject<HTMLDivElement>;
    className?: string | undefined;
    accesskey?: createElement.JSX.Signalish<string | undefined>;
    accessKey?: createElement.JSX.Signalish<string | undefined>;
    autocapitalize?: createElement.JSX.Signalish<"none" | "off" | "on" | "sentences" | "words" | "characters" | undefined>;
    autoCapitalize?: createElement.JSX.Signalish<"none" | "off" | "on" | "sentences" | "words" | "characters" | undefined>;
    autocorrect?: createElement.JSX.Signalish<string | undefined>;
    autoCorrect?: createElement.JSX.Signalish<string | undefined>;
    autofocus?: createElement.JSX.Signalish<boolean | undefined>;
    autoFocus?: createElement.JSX.Signalish<boolean | undefined>;
    class?: createElement.JSX.Signalish<string | undefined>;
    contenteditable?: createElement.JSX.Signalish<"" | "inherit" | import("preact/src/jsx").Booleanish | "plaintext-only" | undefined>;
    contentEditable?: createElement.JSX.Signalish<"" | "inherit" | import("preact/src/jsx").Booleanish | "plaintext-only" | undefined>;
    dir?: createElement.JSX.Signalish<"auto" | "ltr" | "rtl" | undefined>;
    draggable?: createElement.JSX.Signalish<boolean | undefined>;
    enterkeyhint?: createElement.JSX.Signalish<"search" | "next" | "done" | "enter" | "go" | "previous" | "send" | undefined>;
    exportparts?: createElement.JSX.Signalish<string | undefined>;
    hidden?: createElement.JSX.Signalish<boolean | "hidden" | "until-found" | undefined>;
    id?: createElement.JSX.Signalish<string | undefined>;
    inert?: createElement.JSX.Signalish<boolean | undefined>;
    inputmode?: createElement.JSX.Signalish<string | undefined>;
    inputMode?: createElement.JSX.Signalish<string | undefined>;
    is?: createElement.JSX.Signalish<string | undefined>;
    lang?: createElement.JSX.Signalish<string | undefined>;
    nonce?: createElement.JSX.Signalish<string | undefined>;
    part?: createElement.JSX.Signalish<string | undefined>;
    popover?: createElement.JSX.Signalish<boolean | "auto" | "manual" | "hint" | undefined>;
    slot?: createElement.JSX.Signalish<string | undefined>;
    spellcheck?: createElement.JSX.Signalish<boolean | undefined>;
    style?: createElement.JSX.Signalish<string | createElement.JSX.CSSProperties | undefined>;
    tabindex?: createElement.JSX.Signalish<number | undefined>;
    tabIndex?: createElement.JSX.Signalish<number | undefined>;
    title?: createElement.JSX.Signalish<string | undefined>;
    translate?: createElement.JSX.Signalish<boolean | undefined>;
    role?: createElement.JSX.Signalish<createElement.JSX.AriaRole | undefined>;
    disablePictureInPicture?: createElement.JSX.Signalish<boolean | undefined>;
    elementtiming?: createElement.JSX.Signalish<string | undefined>;
    elementTiming?: createElement.JSX.Signalish<string | undefined>;
    results?: createElement.JSX.Signalish<number | undefined>;
    about?: createElement.JSX.Signalish<string | undefined>;
    datatype?: createElement.JSX.Signalish<string | undefined>;
    inlist?: any;
    prefix?: createElement.JSX.Signalish<string | undefined>;
    property?: createElement.JSX.Signalish<string | undefined>;
    resource?: createElement.JSX.Signalish<string | undefined>;
    typeof?: createElement.JSX.Signalish<string | undefined>;
    vocab?: createElement.JSX.Signalish<string | undefined>;
    itemid?: createElement.JSX.Signalish<string | undefined>;
    itemID?: createElement.JSX.Signalish<string | undefined>;
    itemprop?: createElement.JSX.Signalish<string | undefined>;
    itemProp?: createElement.JSX.Signalish<string | undefined>;
    itemref?: createElement.JSX.Signalish<string | undefined>;
    itemRef?: createElement.JSX.Signalish<string | undefined>;
    itemscope?: createElement.JSX.Signalish<boolean | undefined>;
    itemScope?: createElement.JSX.Signalish<boolean | undefined>;
    itemtype?: createElement.JSX.Signalish<string | undefined>;
    itemType?: createElement.JSX.Signalish<string | undefined>;
    key?: any;
    jsx?: boolean | undefined;
    onLoad?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onError?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onErrorCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onCopy?: createElement.JSX.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCopyCapture?: createElement.JSX.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCut?: createElement.JSX.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCutCapture?: createElement.JSX.ClipboardEventHandler<HTMLDivElement> | undefined;
    onPaste?: createElement.JSX.ClipboardEventHandler<HTMLDivElement> | undefined;
    onPasteCapture?: createElement.JSX.ClipboardEventHandler<HTMLDivElement> | undefined;
    onCompositionEnd?: createElement.JSX.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionEndCapture?: createElement.JSX.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionStart?: createElement.JSX.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionStartCapture?: createElement.JSX.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionUpdate?: createElement.JSX.CompositionEventHandler<HTMLDivElement> | undefined;
    onCompositionUpdateCapture?: createElement.JSX.CompositionEventHandler<HTMLDivElement> | undefined;
    onToggle?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onClose?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onCancel?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onFocus?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onFocusCapture?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onFocusIn?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onFocusInCapture?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onFocusOut?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onFocusOutCapture?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onBlur?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onBlurCapture?: createElement.JSX.FocusEventHandler<HTMLDivElement> | undefined;
    onChange?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onChangeCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onInput?: createElement.JSX.InputEventHandler<HTMLDivElement> | undefined;
    onInputCapture?: createElement.JSX.InputEventHandler<HTMLDivElement> | undefined;
    onBeforeInput?: createElement.JSX.InputEventHandler<HTMLDivElement> | undefined;
    onBeforeInputCapture?: createElement.JSX.InputEventHandler<HTMLDivElement> | undefined;
    onSearch?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSearchCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSubmit?: createElement.JSX.SubmitEventHandler<HTMLDivElement> | undefined;
    onSubmitCapture?: createElement.JSX.SubmitEventHandler<HTMLDivElement> | undefined;
    onInvalid?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onInvalidCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onReset?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onResetCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onFormData?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onFormDataCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onKeyDown?: createElement.JSX.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyDownCapture?: createElement.JSX.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyPress?: createElement.JSX.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyPressCapture?: createElement.JSX.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyUp?: createElement.JSX.KeyboardEventHandler<HTMLDivElement> | undefined;
    onKeyUpCapture?: createElement.JSX.KeyboardEventHandler<HTMLDivElement> | undefined;
    onAbort?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onAbortCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onCanPlay?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onCanPlayCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onCanPlayThrough?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onCanPlayThroughCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onDurationChange?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onDurationChangeCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onEmptied?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onEmptiedCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onEncrypted?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onEncryptedCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onEnded?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onEndedCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadedData?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadedDataCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadedMetadata?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadedMetadataCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadStart?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onLoadStartCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onPause?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onPauseCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onPlay?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onPlayCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onPlaying?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onPlayingCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onProgress?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onProgressCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onRateChange?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onRateChangeCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSeeked?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSeekedCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSeeking?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSeekingCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onStalled?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onStalledCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSuspend?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSuspendCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onTimeUpdate?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onTimeUpdateCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onVolumeChange?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onVolumeChangeCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onWaiting?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onWaitingCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onClick?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onClickCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onContextMenu?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onContextMenuCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onDblClick?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onDblClickCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onDrag?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragEnd?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragEndCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragEnter?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragEnterCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragExit?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragExitCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragLeave?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragLeaveCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragOver?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragOverCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragStart?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDragStartCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDrop?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onDropCapture?: createElement.JSX.DragEventHandler<HTMLDivElement> | undefined;
    onMouseDown?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseDownCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseEnter?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseEnterCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseLeave?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseLeaveCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseMove?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseMoveCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOut?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOutCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOver?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseOverCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseUp?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onMouseUpCapture?: createElement.JSX.MouseEventHandler<HTMLDivElement> | undefined;
    onSelect?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onSelectCapture?: createElement.JSX.GenericEventHandler<HTMLDivElement> | undefined;
    onTouchCancel?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchCancelCapture?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchEnd?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchEndCapture?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchMove?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchMoveCapture?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchStart?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onTouchStartCapture?: createElement.JSX.TouchEventHandler<HTMLDivElement> | undefined;
    onPointerOver?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOverCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerEnter?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerEnterCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerDown?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerDownCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerMove?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerMoveCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerUp?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerUpCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerCancel?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerCancelCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOut?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerOutCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerLeave?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onPointerLeaveCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onGotPointerCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onGotPointerCaptureCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onLostPointerCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onLostPointerCaptureCapture?: createElement.JSX.PointerEventHandler<HTMLDivElement> | undefined;
    onScroll?: createElement.JSX.UIEventHandler<HTMLDivElement> | undefined;
    onScrollEnd?: createElement.JSX.UIEventHandler<HTMLDivElement> | undefined;
    onScrollCapture?: createElement.JSX.UIEventHandler<HTMLDivElement> | undefined;
    onWheel?: createElement.JSX.WheelEventHandler<HTMLDivElement> | undefined;
    onWheelCapture?: createElement.JSX.WheelEventHandler<HTMLDivElement> | undefined;
    onAnimationStart?: createElement.JSX.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationStartCapture?: createElement.JSX.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationEnd?: createElement.JSX.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationEndCapture?: createElement.JSX.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationIteration?: createElement.JSX.AnimationEventHandler<HTMLDivElement> | undefined;
    onAnimationIterationCapture?: createElement.JSX.AnimationEventHandler<HTMLDivElement> | undefined;
    onTransitionCancel?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionCancelCapture?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionEnd?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionEndCapture?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionRun?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionRunCapture?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionStart?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onTransitionStartCapture?: createElement.JSX.TransitionEventHandler<HTMLDivElement> | undefined;
    onEnterPictureInPicture?: createElement.JSX.PictureInPictureEventHandler<HTMLDivElement> | undefined;
    onEnterPictureInPictureCapture?: createElement.JSX.PictureInPictureEventHandler<HTMLDivElement> | undefined;
    onLeavePictureInPicture?: createElement.JSX.PictureInPictureEventHandler<HTMLDivElement> | undefined;
    onLeavePictureInPictureCapture?: createElement.JSX.PictureInPictureEventHandler<HTMLDivElement> | undefined;
    onResize?: createElement.JSX.PictureInPictureEventHandler<HTMLDivElement> | undefined;
    onResizeCapture?: createElement.JSX.PictureInPictureEventHandler<HTMLDivElement> | undefined;
    dangerouslySetInnerHTML?: {
        __html: string;
    } | undefined;
    'aria-activedescendant'?: createElement.JSX.Signalish<string | undefined>;
    'aria-atomic'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-autocomplete'?: createElement.JSX.Signalish<"inline" | "both" | "none" | "list" | undefined>;
    'aria-braillelabel'?: createElement.JSX.Signalish<string | undefined>;
    'aria-brailleroledescription'?: createElement.JSX.Signalish<string | undefined>;
    'aria-busy'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-checked'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | "mixed" | undefined>;
    'aria-colcount'?: createElement.JSX.Signalish<number | undefined>;
    'aria-colindex'?: createElement.JSX.Signalish<number | undefined>;
    'aria-colindextext'?: createElement.JSX.Signalish<string | undefined>;
    'aria-colspan'?: createElement.JSX.Signalish<number | undefined>;
    'aria-controls'?: createElement.JSX.Signalish<string | undefined>;
    'aria-current'?: createElement.JSX.Signalish<"location" | "time" | import("preact/src/jsx").Booleanish | "page" | "step" | "date" | undefined>;
    'aria-describedby'?: createElement.JSX.Signalish<string | undefined>;
    'aria-description'?: createElement.JSX.Signalish<string | undefined>;
    'aria-details'?: createElement.JSX.Signalish<string | undefined>;
    'aria-disabled'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-dropeffect'?: createElement.JSX.Signalish<"link" | "none" | "copy" | "move" | "execute" | "popup" | undefined>;
    'aria-errormessage'?: createElement.JSX.Signalish<string | undefined>;
    'aria-expanded'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-flowto'?: createElement.JSX.Signalish<string | undefined>;
    'aria-grabbed'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-haspopup'?: createElement.JSX.Signalish<"grid" | "dialog" | "menu" | import("preact/src/jsx").Booleanish | "listbox" | "tree" | undefined>;
    'aria-hidden'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-invalid'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | "grammar" | "spelling" | undefined>;
    'aria-keyshortcuts'?: createElement.JSX.Signalish<string | undefined>;
    'aria-label'?: createElement.JSX.Signalish<string | undefined>;
    'aria-labelledby'?: createElement.JSX.Signalish<string | undefined>;
    'aria-level'?: createElement.JSX.Signalish<number | undefined>;
    'aria-live'?: createElement.JSX.Signalish<"off" | "assertive" | "polite" | undefined>;
    'aria-modal'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-multiline'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-multiselectable'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-orientation'?: createElement.JSX.Signalish<"horizontal" | "vertical" | undefined>;
    'aria-owns'?: createElement.JSX.Signalish<string | undefined>;
    'aria-placeholder'?: createElement.JSX.Signalish<string | undefined>;
    'aria-posinset'?: createElement.JSX.Signalish<number | undefined>;
    'aria-pressed'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | "mixed" | undefined>;
    'aria-readonly'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-relevant'?: createElement.JSX.Signalish<"all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined>;
    'aria-required'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-roledescription'?: createElement.JSX.Signalish<string | undefined>;
    'aria-rowcount'?: createElement.JSX.Signalish<number | undefined>;
    'aria-rowindex'?: createElement.JSX.Signalish<number | undefined>;
    'aria-rowindextext'?: createElement.JSX.Signalish<string | undefined>;
    'aria-rowspan'?: createElement.JSX.Signalish<number | undefined>;
    'aria-selected'?: createElement.JSX.Signalish<import("preact/src/jsx").Booleanish | undefined>;
    'aria-setsize'?: createElement.JSX.Signalish<number | undefined>;
    'aria-sort'?: createElement.JSX.Signalish<"none" | "ascending" | "descending" | "other" | undefined>;
    'aria-valuemax'?: createElement.JSX.Signalish<number | undefined>;
    'aria-valuemin'?: createElement.JSX.Signalish<number | undefined>;
    'aria-valuenow'?: createElement.JSX.Signalish<number | undefined>;
    'aria-valuetext'?: createElement.JSX.Signalish<string | undefined>;
}>;
